<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>CSharpDiscordWebhook</PackageId>
        <Version>3.0.1</Version>
        <Authors>NatanM</Authors>
        <PackageDescription>A simple C# wrapper for Discord webhooks</PackageDescription>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/MrNatanael/CSharpDiscordWebhook</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="../LICENSE" Pack="true" PackagePath="/" />
        <None Include="../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>
</Project>
